//要点：数据类的copy()函数
/**
 * Data class gets next functions, generated automatically:
 * 数据类 获得的（特有的） 下一个函数，自动产生函数：
 * component functions, toString(), equals(), hashCode() and copy().
 * 部件函数，... 和 copy()函数。
 * See http://kotlinlang.org/docs/reference/data-classes.html#data-classes
 */
package autogenerated  //为了避免自定义类名称冲突

data class User(val name: String, val id: Int)  //数据类

fun main(args: Array<String>) {
    val user = User("Alex", 1)
    println(user) // toString()

    val secondUser = User("Alex", 1)
    val thirdUser = User("Max", 2)

    println("user == secondUser: ${user == secondUser}")
    println("user == thirdUser: ${user == thirdUser}")

    // copy() function
    println(user.copy())   //数据类的copy()函数
    println(user.copy("Max"))
    println(user.copy(id = 2))
    println(user.copy("Max", 2))
}

//User(name=Alex, id=1)
//user == secondUser: true
//user == thirdUser: false
//User(name=Alex, id=1)
//User(name=Max, id=1)
//User(name=Alex, id=2)
//User(name=Max, id=2)